---
title: Blikveld
timezone: UTC
collections:
  films:
    title: Films
    output: true
    url: films
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Een filmfestival op locatie
keywords: film
baseurl: "/blikveld"
exclude:
- README.md
include:
- _pages
permalink: "/:title/"
navi:
- name: Home
  url: "/"
  class: 
  rel: 
- name: Programma
  url: "/programma"
  class: 
  rel: 
- name: Tickets
  url: "/tickets"
  class: 
  rel: 
- name: Locaties
  url: "/locaties"
  class: 
  rel: 
- name: Praktisch
  url: "/praktisch"
  class: 
  rel: 
- name: Missie
  url: "/missie"
  class: 
  rel: 
team:
- name: Hans 't Kindt
  image: team-hans.jpg
  text: kloppend hart van de organisatie <br />woont in Etikhove <br />kijkt uit naar
    Late Night Special
- name: Piet De Loof
  image: team-piet.jpg
  text: schrijft alle copy voor web en print <br />woont in Leupegem <br />kijkt uit
    naar 'Days of heaven'
- name: Rosalien Eggermont
  image: team-rosalien.jpg
  text: grafisch vormgeefster van Blikveld <br />woont in Leupegem
- name: Ludo Vander Haeghen
  image: team-ludo.jpg
  text: Ludo, de man achter de cijfers
- name: Bert Van Wassenhove
  image: team-bert.jpg
  text: digitale marketing specialist <br />investeert in innovatieve ondernemingen
    <br />vond de liefde in Maarkedal
- name: Els De Deken
  image: team-els.jpg
  text: community manager en matchmaker voor THINK with people <br />groeide op, op
    100m van de kerk van Kerkem
- name: Tim Maerschand
  image: team-tim.jpg
  text: programmator, woont in Gent <br />kijkt uit naar de reacties van het publiek,
    jong en oud
