# SITE SETTINGS
title: Blikveld
description: Een filmfestival op locatie
keywords: film
baseurl: /blikveld
exclude: ['README.md']
include: ['_pages']
permalink: /:title/

# NAVIGATION
navi:
  wat:
    name: wat
    url: /wat
  waar:
    name: waar
    url: /waar
  wanneer:
    name: wanneer
    url: /wanneer
    
# COLLECTIONS
collections:
  films:
    output: true
    url: films