# SITE SETTINGS
title: Dit is een website
description: Dit is een omschrijving
keywords: film
baseurl: /blikveld
exclude: ['README.md']


# NAVIGATION
navi:
  wat:
    name: wat
    url: /wat
  waar:
    name: waar
    url: /waar
  wanneer:
    name: wanneer
    url: /wanneer
    
# COLLECTIONS
collections:
  movies
