# SITE SETTINGS
title: Blikveld
description: Een filmfestival op locatie
keywords: film
baseurl: /blikveld
exclude: ['README.md']
include: ['_pages']
permalink: /:title/

# NAVIGATION
navi:
- name: Home
  url: /
  class: 
  rel: 
- name: Films
  url: /films
  class: 
  rel: 
- name: Tickets
  url: /tickets
  class: 
  rel: 
- name: Praktisch
  url: /praktisch
  class: 
  rel: 
- name: Missie
  url: /missie
  class: 
  rel: 
    
# COLLECTIONS
collections:
  films:
    output: true
    url: films