---
title: Blikveld
timezone: UTC
collections:
  films:
    title: Films
    output: true
    url: films
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Filmfestival Vlaamse Ardennen
keywords: film
baseurl: ''
exclude:
- README.md
include:
- _pages
permalink: "/:title/"
navi:
- name: Home
  url: "/"
  class: 
  rel: 
- name: Programma
  url: "/programma"
  class: 
  rel: 
- name: Locatie
  url: "/locatie"
  class: 
  rel: 
- name: Praktisch
  url: "/praktisch"
  class: 
  rel: 
- name: Missie
  url: "/missie"
  class: 
  rel: 
