# SITE SETTINGS
title: Blikveld
description: Een filmfestival op locatie
keywords: film
baseurl: /blikveld
exclude: ['README.md']
include: ['_pages']
permalink: /:title/

# NAVIGATION
navi:
- name: Home
  url: /
  class: 
  rel: 
- name: Programma
  url: /programma
  class: 
  rel: 
- name: Tickets
  url: /tickets
  class: 
  rel: 
- name: Locaties
  url: /locaties
  class: 
  rel: 
- name: Praktisch
  url: /praktisch
  class: 
  rel: 
- name: Missie
  url: /missie
  class: 
  rel: 
    
# COLLECTIONS
collections:
  films:
    output: true
    url: films
    
# TEAM
team:
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special