---
title: Blikveld
timezone: UTC
collections:
  films:
    title: Films
    output: true
    url: films
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Een filmfestival op locatie
keywords: film
baseurl: "/blikveld"
exclude:
- README.md
include:
- _pages
permalink: "/:title/"
navi:
- name: Home
  url: "/"
  class: 
  rel: 
- name: Programma
  url: "/programma"
  class: 
  rel: 
- name: Tickets
  url: "/tickets"
  class: 
  rel: 
- name: Locaties
  url: "/locaties"
  class: 
  rel: 
- name: Praktisch
  url: "/praktisch"
  class: 
  rel: 
- name: Missie
  url: "/missie"
  class: 
  rel: 
team:
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Piet De Loof
  age: 45
  image: team-piet.jpg
  one: schrijft alle copy voor web en print
  two: woont in Leupegem
  three: kijkt uit naar 'Days of heaven'
- name: Rosalien Eggermont
  age: 29
  image: team-hans.jpg
  one: grafisch vormgeefster van Blikveld
  two: woont in Leupegem
  three: kijkt uit naar de openingsfilm
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
- name: Hans 't Kindt
  age: 50
  image: team-hans.jpg
  one: kloppend hart van de organisatie
  two: woont in Etikhove
  three: kijkt uit naar Late Night Special
