---
title: Blikveld
timezone: UTC
collections:
  films:
    title: Films
    output: true
    url: films
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Een filmfestival op locatie
keywords: film
baseurl: ''
exclude:
- README.md
include:
- _pages
permalink: "/:title/"
navi:
- name: Home
  url: "/"
  class: 
  rel: 
- name: Programma
  url: "/programma"
  class: 
  rel: 
- name: Tickets
  url: http://blikveld.eventbrite.com/
  class: 
  rel: external
- name: Locaties
  url: "/locaties"
  class: 
  rel: 
- name: Praktisch
  url: "/praktisch"
  class: 
  rel: 
- name: Missie
  url: "/missie"
  class: 
  rel: 
team:
- name: Hans<br />'t Kindt
  image: team-hans.jpg
  text: kloppend hart van de organisatie,<br />woont in Etikhove,<br />kijkt uit naar
    Late Night Special
- name: Piet<br />De Loof
  image: team-piet.jpg
  text: schrijft alle copy voor web en print,<br />woont in Leupegem,<br />kijkt uit
    naar 'Days of heaven'
- name: Rosalien<br />Eggermont
  image: team-rosalien.jpg
  text: grafisch vormgeefster van Blikveld,<br />woont in Leupegem
- name: Ludo<br />Vander Haeghen
  image: team-ludo.jpg
  text: Ludo, de man achter de cijfers
- name: Bert<br />Van Wassenhove
  image: team-bert.jpg
  text: digitale marketing specialist,<br />investeert in innovatieve ondernemingen,<br
    />vond de liefde in Maarkedal
- name: Els<br />De Deken
  image: team-els.jpg
  text: community manager en matchmaker voor THINK with people,<br />groeide op, op
    100m van de kerk van Kerkem
- name: Tim<br />Maerschand
  image: team-tim.jpg
  text: programmator, woont in Gent,<br />kijkt uit naar de reacties van het publiek,
    jong en oud
- name: Fréderic<br />Verwee
  image: team-frederic.jpg
  text: unieke films op prachtige locaties voor het goede doel! <br />Een bijzonder
    combinatie!
- name: Anthony<br />Claeys
  image: team-anthony.jpg
  text: woont in Ronse,<br />sociaal geëngageerd en niet vies om zelf handen uit de
    mouwen te steken!
- name: Matthias<br />Peynshaert
  image: team-matthias.jpg
  text: melomaan, cinefiel, megalomaan
- name: Pieter<br />Uytterschaut
  image: team-pieter.jpg
  text: Oudenaardist, cultuurliefhebber en marketeer. Geen uitdaging ga ik uit de
    weg om Sociale projecten te ondersteunen
- name: Yves<br />Van Langenhove
  image: team-yves.jpg
  text: woont in Etikhove,<br />zet met veel overtuiging zijn schouders onder dit
    uitzonderlijke project tbv onze sociale projecten
- name: Nelson<br />Vroman
  image: team-nelson.jpg
  text: zet graag zijn schouders onder dit uniek festival
